Update build_android_signed.yml

diff --git a/.github/workflows/build_android_signed.yml b/.github/workflows/build_android_signed.yml
--- a/.github/workflows/build_android_signed.yml
+++ b/.github/workflows/build_android_signed.yml
@@ -203,28 +203,28 @@ jobs:
             if [[ -f "$QT_BINDINGS_DIR/QtLoader.java" ]]; then
               echo "Replacing $QT_BINDINGS_DIR/QtLoader.java"
               cat > "$QT_BINDINGS_DIR/QtLoader.java" <<'EOF'
-        package org.qtproject.qt5.android.bindings;
-        
-        import android.app.Activity;
-        import android.content.Intent;
-        import android.os.Bundle;
-        
-        public class QtLoader extends Activity {
-            @Override
-            protected void onCreate(Bundle savedInstanceState) {
-                super.onCreate(savedInstanceState);
-                Intent intent = new Intent(getApplicationContext(), QOpenHDActivity.class);
-                intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
-                getApplicationContext().startActivity(intent);
-                finish();
+            package org.qtproject.qt5.android.bindings;
+            
+            import android.app.Activity;
+            import android.content.Intent;
+            import android.os.Bundle;
+            
+            public class QtLoader extends Activity {
+                @Override
+                protected void onCreate(Bundle savedInstanceState) {
+                    super.onCreate(savedInstanceState);
+                    Intent intent = new Intent(getApplicationContext(), QOpenHDActivity.class);
+                    intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
+                    getApplicationContext().startActivity(intent);
+                    finish();
+                }
             }
-        }
-        EOF
-            else
-              echo "QtLoader.java not found, build may fail."
-              exit 1
-            fi
-        
+            EOF
+                else
+                  echo "QtLoader.java not found, build may fail."
+                  exit 1
+                fi
+            
       - name: list failiours
         if: failure()
         working-directory: ${{ github.workspace }}/lib/gstreamer_prebuilts
