Update build_android_signed.yml

diff --git a/.github/workflows/build_android_signed.yml b/.github/workflows/build_android_signed.yml
--- a/.github/workflows/build_android_signed.yml
+++ b/.github/workflows/build_android_signed.yml
@@ -110,12 +110,21 @@ jobs:
         env:
           NDK_ROOT: ${{ steps.setup-ndk.outputs.ndk-path }}
         run: |
-          export API=21
+          export API=35
           export TOOLCHAIN=$NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64
 
-          echo "AR binary: $AR"
+          if [[ "$ARCH" == "arm64" ]]; then
+            AR="$ANDROID_NDK/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar"
+          elif [[ "$ARCH" == "armv7" ]]; then
+            AR="$ANDROID_NDK/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar"
+          else
+            echo "[ERROR] Unknown arch: $ARCH"
+            exit 1
+          fi
+
+          echo "Using AR: $AR"
           ls -l "$AR"
-          
+
           if [[ "${{ matrix.architecture }}" == "armv7" ]]; then
             export TARGET=armv7a-linux-androideabi
             export CC=$TOOLCHAIN/bin/${TARGET}${API}-clang
