Update build_android_signed_qt6.yml

diff --git a/.github/workflows/build_android_signed_qt6.yml b/.github/workflows/build_android_signed_qt6.yml
--- a/.github/workflows/build_android_signed_qt6.yml
+++ b/.github/workflows/build_android_signed_qt6.yml
@@ -75,11 +75,44 @@ jobs:
       - name: Create build directory
         run: mkdir -p ${{ runner.temp }}/shadow_build_dir
 
-      - name: Install GStreamer (optional, keep if needed)
-        working-directory: ${{ github.workspace }}
+      - name: Install GStreamer & FFmpeg (matching arch)
+        working-directory: ${{ github.workspace }}/lib/gstreamer_prebuilts
+        env:
+          NDK_ROOT: ${{ steps.setup-ndk.outputs.ndk-path }}
         run: |
-          cd lib/gstreamer_prebuilts/
-          ./fetch_extract_locally.sh
+          export API=35
+          export TOOLCHAIN=$NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64
+          export RANLIB="$NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ranlib"
+
+
+          ls /usr/local/lib/android/sdk/platforms/android-35/
+
+          if [[ "${{ matrix.architecture }}" == "armv8" ]]; then
+            AR="$ANDROID_NDK/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar"
+          elif [[ "${{ matrix.architecture }}" == "armv7" ]]; then
+            AR="$ANDROID_NDK/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar"
+          else
+            echo "[ERROR] Unknown arch: $ARCH"
+            exit 1
+          fi
+
+          echo "Using AR: $AR"
+          ls -l "$AR"
+
+          if [[ "${{ matrix.architecture }}" == "armv7" ]]; then
+            export TARGET=armv7a-linux-androideabi
+            export CC=$TOOLCHAIN/bin/${TARGET}${API}-clang
+            export AR=$TOOLCHAIN/bin/llvm-ar
+            ./fetch_extract_locally.sh -armv7
+          elif [[ "${{ matrix.architecture }}" == "armv8" ]]; then
+            export TARGET=aarch64-linux-android
+            export CC=$TOOLCHAIN/bin/${TARGET}${API}-clang
+            export AR=$TOOLCHAIN/bin/llvm-ar
+            ./fetch_extract_locally.sh -arm64
+          else
+            echo "Unsupported architecture: ${{ matrix.architecture }}"
+            exit 1
+          fi
 
       - name: Configure (CMake for Android Qt6)
         working-directory: ${{ runner.temp }}/shadow_build_dir
